package Only_Admin_UAT;

import java.awt.Robot;
import java.awt.event.KeyEvent;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.Select;

public class ZA3_Manage_Orders_Trans_Hold {

	public static void main(String[] args) throws Exception {
		System.setProperty("webdriver.gecko.driver", "./Resources/geckodriver.exe");
		WebDriver driver = new FirefoxDriver();
		driver.manage().window().maximize();
		driver.navigate().to("https://daaz_uat:daaz_uat@2020@teams.daaz.xyz/admin/view/all/domain/history");
		System.out.println("Enter admin");
		Thread.sleep(2000);
		driver.findElement(By.id("username")).sendKeys("UAT_DaaZ_Admin");
		Thread.sleep(2000);
		driver.findElement(By.id("password")).sendKeys("UATAdmin@2020");
		Thread.sleep(1000);
		
		//driver.findElement(By.id("signInBtn")).click();	
		 JavascriptExecutor jsee= (JavascriptExecutor)driver;
	   	 jsee.executeScript("document.getElementById('signInBtn').value='Dev_DaaZ_Admin';");		
	   	jsee.executeScript("document.getElementById('signInBtn').setAttribute('style','border:10px red solid;background:yellow;color:green');");
	   	driver.findElement(By.id("signInBtn")).click();
	   	Thread.sleep(1000);
		System.out.println("Admin Login succuss");
		Thread.sleep(2000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("/html/body/div[1]/div[4]/div[1]/div/ul/li[7]/a")).click();// Manage Orders
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div/div[4]/div[1]/div/ul/li[7]/ul/li[2]/a")).click();// Transactions on Hold
		Thread.sleep(2000);
		//driver.findElement(By.xpath("/html/body/div[1]/div[4]/div[2]/div/div[2]/div/div/div[1]/div[2]/input[3]")).click();//Balance
		Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[1]/div[1]/div[1]/div/a[2]/i")).click();
        Thread.sleep(2000);
        Select std=new Select(driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[1]/div[1]/div[2]/label/select")));
        std.selectByIndex(1);
        Thread.sleep(2000);
        std.selectByIndex(2);
        Thread.sleep(2000);
        std.selectByIndex(3);
        Thread.sleep(2000);
        std.selectByIndex(4);
        Thread.sleep(2000);
        std.selectByIndex(5);
        Thread.sleep(2000);
        std.selectByIndex(1);
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/table/thead/tr[2]/td[2]/input")).sendKeys("00404758LE2820312");
        Thread.sleep(2000);
        Robot rb=new Robot();
        rb.keyPress(KeyEvent.VK_ENTER);
        rb.keyRelease(KeyEvent.VK_ENTER);
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/table/thead/tr[2]/td[12]/div/button[2]")).click();
        Thread.sleep(2000);
        driver.findElement(By.name("paypal_id")).sendKeys("6X943166AN169043R");
        Thread.sleep(2000);
        Robot rt=new Robot();
        rt.keyPress(KeyEvent.VK_ENTER); 
        rt.keyRelease(KeyEvent.VK_ENTER);
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/table/thead/tr[2]/td[12]/div/button[2]")).click();
        Thread.sleep(2000);
        driver.findElement(By.name("domain_name")).sendKeys("aucttionmo.co");
        Thread.sleep(2000);
        Robot rqt=new Robot();
        rqt.keyPress(KeyEvent.VK_ENTER); 
        rqt.keyRelease(KeyEvent.VK_ENTER);
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/table/thead/tr[2]/td[12]/div/button[2]")).click();
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div[1]/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/table/thead/tr[2]/td[5]/div/span/button")).click();
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div[2]/div[1]/table/thead/tr[2]/th[1]")).click();
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div[2]/div[1]/table/thead/tr[2]/th[1]")).click();
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div[2]/div[1]/table/thead/tr[2]/th[1]")).click();
        Thread.sleep(2000);        
        driver.findElement(By.xpath("/html/body/div[2]/div[1]/table/tbody/tr[3]/td[6]")).click();
        Thread.sleep(2000); 
        Robot rqtq=new Robot();
        rqtq.keyPress(KeyEvent.VK_ENTER); 
        rqtq.keyRelease(KeyEvent.VK_ENTER);
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/table/thead/tr[2]/td[12]/div/button[2]")).click();
        Thread.sleep(2000);
        driver.findElement(By.name("email")).sendKeys("rakeshuppula3@gmail.com");
        Thread.sleep(2000); 
        Robot rqqt=new Robot();
        rqqt.keyPress(KeyEvent.VK_ENTER); 
        rqqt.keyRelease(KeyEvent.VK_ENTER);
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/table/thead/tr[2]/td[12]/div/button[2]")).click();
        Thread.sleep(2000);
        driver.findElement(By.name("grand_total")).sendKeys("15");
        Robot qt=new Robot();
        qt.keyPress(KeyEvent.VK_ENTER); 
        qt.keyRelease(KeyEvent.VK_ENTER);
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/table/thead/tr[2]/td[12]/div/button[2]")).click();
        Thread.sleep(2000);
        driver.findElement(By.name("total_paid")).sendKeys("24");
        Robot qn=new Robot();
        qn.keyPress(KeyEvent.VK_ENTER); 
        qn.keyRelease(KeyEvent.VK_ENTER);
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/table/thead/tr[2]/td[12]/div/button[2]")).click();
        Thread.sleep(2000);
        driver.findElement(By.name("currency")).sendKeys("GBP");
        Thread.sleep(2000);
        Robot qnb=new Robot();
        qnb.keyPress(KeyEvent.VK_ENTER); 
        qnb.keyRelease(KeyEvent.VK_ENTER);
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/table/thead/tr[2]/td[12]/div/button[2]")).click();
        Thread.sleep(2000);
        driver.findElement(By.name("currency")).sendKeys("EUR");
        Thread.sleep(2000);
        Robot qnb1=new Robot();
        qnb1.keyPress(KeyEvent.VK_ENTER); 
        qnb1.keyRelease(KeyEvent.VK_ENTER);
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/table/thead/tr[2]/td[12]/div/button[2]")).click();
        Thread.sleep(2000);
        driver.findElement(By.name("currency")).sendKeys("USD");
        Thread.sleep(2000);
        Robot qnk=new Robot();
        qnk.keyPress(KeyEvent.VK_ENTER); 
        qnk.keyRelease(KeyEvent.VK_ENTER);
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/table/thead/tr[2]/td[12]/div/button[2]")).click();
        Thread.sleep(2000);
        Select sj=new Select(driver.findElement(By.name("price_option")));
//        JavascriptExecutor jse= (JavascriptExecutor)driver;
//      	 jse.executeScript("document.getElementsByname('currency').value='Dev_DaaZ_Admin';");		
//       	 jse.executeScript("document.getElementsByname('currency').setAttribute('style','border:5px red solid;background:yellow;color:green');");
      	Thread.sleep(2000);
        sj.selectByIndex(1);
        Thread.sleep(2000);
        Robot qnke=new Robot();
        qnke.keyPress(KeyEvent.VK_ENTER); 
        qnke.keyRelease(KeyEvent.VK_ENTER);
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/table/thead/tr[2]/td[12]/div/button[2]")).click();
        Thread.sleep(2000);
        sj.selectByIndex(2);
        Thread.sleep(2000);
        Robot qnked=new Robot();
        qnked.keyPress(KeyEvent.VK_ENTER); 
        qnked.keyRelease(KeyEvent.VK_ENTER);
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/table/thead/tr[2]/td[12]/div/button[2]")).click();
        Thread.sleep(2000);
        Select ok=new Select(driver.findElement(By.name("type")));
        ok.selectByIndex(1);
        Thread.sleep(2000);
        Robot ok1=new Robot();
        ok1.keyPress(KeyEvent.VK_ENTER); 
        ok1.keyRelease(KeyEvent.VK_ENTER);
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/table/thead/tr[2]/td[12]/div/button[2]")).click();
        Thread.sleep(2000);
        
        ok.selectByIndex(2);
        Thread.sleep(2000);
        Robot ok3=new Robot();
        ok3.keyPress(KeyEvent.VK_ENTER); 
        ok3.keyRelease(KeyEvent.VK_ENTER);
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/table/thead/tr[2]/td[12]/div/button[2]")).click();
        Thread.sleep(2000);
        ok.selectByIndex(3);
        Thread.sleep(2000);
        Robot ok4=new Robot();
        ok4.keyPress(KeyEvent.VK_ENTER); 
        ok4.keyRelease(KeyEvent.VK_ENTER);
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/table/thead/tr[2]/td[12]/div/button[2]")).click();
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[1]/div[2]/a")).click();
        Thread.sleep(2000);
        driver.findElement(By.id("domain_name")).sendKeys("Ameerpet.in");
        Thread.sleep(2000);
        driver.findElement(By.id("transID")).sendKeys("evmakerew3wwnetoljjkk");
        Thread.sleep(2000);
        driver.findElement(By.id("email")).sendKeys("rakeshuppula3+buyer@gmail.com");
        Thread.sleep(2000);
        driver.findElement(By.id("amount_paid")).sendKeys("500");
        Thread.sleep(2000);
       
        Select bij=new Select(driver.findElement(By.id("payment_method")));
        bij.selectByIndex(1);
        Thread.sleep(2000);
        driver.findElement(By.id("datepicker")).click();
        Thread.sleep(2000);
        driver.findElement(By.xpath("/html/body/div[3]/div[1]/table/tbody/tr[4]/td[7]")).click();
        Thread.sleep(2000);
        driver.findElement(By.id("create_transaction")).click();
        Thread.sleep(5000);
        
        
        driver.findElement(By.xpath("/html/body/div/div[4]/div[1]/div/ul/li[7]/ul/li[2]/a")).click();// Transactions on Hold
		Thread.sleep(2000);
		 driver.findElement(By.xpath("/html/body/div/div[4]/div[2]/div/div[2]/div/div/div[1]/div[2]/a")).click();
	        Thread.sleep(2000);
	        Select fb=new Select(driver.findElement(By.id("transaction_type")));
	        fb.selectByIndex(2);
	        Thread.sleep(2000);
	        driver.findElement(By.id("domain_name")).sendKeys("Mushrooms8100.in");
	        Thread.sleep(2000);
	        driver.findElement(By.id("transID")).sendKeys("evmakerew3wwnetjjj");
	        Thread.sleep(2000);
	        driver.findElement(By.id("email")).sendKeys("rakeshuppula3+buyer@gmail.com");
	        Thread.sleep(2000);
	        driver.findElement(By.id("amount_paid")).sendKeys("500");
	        Thread.sleep(2000);
	        //driver.findElement(By.id("amount_paid")).sendKeys("500");
	        Select bij1=new Select(driver.findElement(By.id("payment_method")));
	        bij1.selectByIndex(1);
	        Thread.sleep(2000);
	        driver.findElement(By.id("datepicker")).click();
	        Thread.sleep(2000);
	        driver.findElement(By.xpath("/html/body/div[3]/div[1]/table/tbody/tr[4]/td[7]")).click();
	        Thread.sleep(2000);
	        driver.findElement(By.id("create_transaction")).click();
	        Thread.sleep(5000);
        
        driver.quit();

	}

}
