package Regression_Testing_DEV;

import java.util.Set;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
public class _904_Settings {
	public static void main(String[] args) throws Exception {
		System.setProperty("webdriver.gecko.driver","./Resources/geckodriver.exe");
		WebDriver driver=new FirefoxDriver();
		driver.manage().window().maximize();
		driver.navigate().to("https://dev:Devserver@1956!2023@d-v.in/edit/profile");
	    Thread.sleep(1000);	    
	     //driver.findElement(By.xpath("/html/body/nav/div[1]/div[2]/div/div[2]/div[2]/ul/li[1]/a")).click();
	     System.out.println("Click on Login Button");
	     driver.findElement(By.id("username")).sendKeys("rakeshuppula3@gmail.com");
	     Thread.sleep(1000);
	     driver.findElement(By.id("password")).sendKeys("Rakesh1800##@@");
	     driver.switchTo().frame("mtcaptcha-1-iframe-1");
		 driver.findElement(By.id("mtcap-inputtext-1")).click();
		 driver.switchTo().defaultContent();
	     Thread.sleep(10000);
	     driver.findElement(By.id("login_submit")).click();
	     System.out.println("LOGIN successfully");
	     Thread.sleep(3000);
	     Thread.sleep(1000);
	     driver.findElement(By.xpath("/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[1]/div[1]/div[3]/div[2]/div[1]/button[1]")).click();	    
	     Thread.sleep(1000);
	     System.out.println("Copy DAAZ ID");
	     driver.findElement(By.xpath("/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[1]/div[1]/div[5]/div[1]/div[1]/input[1]")).sendKeys("Rakesh1800##@@1");
	     Thread.sleep(1000);
	     driver.findElement(By.xpath("/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[1]/div[1]/div[5]/div[2]/div[1]/input[1]")).sendKeys("Rakesh1800##@@1");
	     Thread.sleep(1000);
	     driver.findElement(By.xpath("/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[1]/div[1]/div[6]/input[1]")).click();
	     Thread.sleep(5000);
	     driver.navigate().refresh();
	     driver.findElement(By.xpath("/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[1]/div[1]/div[5]/div[1]/div[1]/input[1]")).sendKeys("Rakesh1800##@@");
	     Thread.sleep(1000);
	     driver.findElement(By.xpath("/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[1]/div[1]/div[5]/div[2]/div[1]/input[1]")).sendKeys("Rakesh1800##@@");
	     Thread.sleep(1000);
	     driver.findElement(By.xpath("/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[1]/div[1]/div[6]/input[1]")).click();	     
	     System.out.println("New Password");
	     Thread.sleep(5000);
	     driver.navigate().refresh();
	     driver.findElement(By.xpath("/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[1]/div[1]/div[9]/div[1]/div[1]/div[2]/input[1]")).click();
	     Thread.sleep(4000);
	     driver.findElement(By.xpath("/html/body/div[6]/div/div/div/div[2]/div/div[3]/div/input")).sendKeys("666643");
	     Thread.sleep(1000);
	     driver.findElement(By.xpath("/html/body/div[6]/div/div/div/div[3]/button[1]")).click();
	     Thread.sleep(1000);
	     driver.findElement(By.xpath("//*[@id=\"exampleModal5\"]/div/div/div[3]/button[2]")).click();
	     Thread.sleep(1000);
	     System.out.println(" 2FA ");
	     driver.findElement(By.xpath("/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[1]/div[1]/div[11]/div[2]/div[1]/button[1]")).click();
	     Thread.sleep(1000);
	     System.out.println("Copy API KEY");	     
	    // driver.findElement(By.id("username")).clear();
	     driver.findElement(By.id("username")).sendKeys("$eller1");
	     Thread.sleep(1000);
	     System.out.println("User name");
	    // driver.findElement(By.id("first_name")).clear();   
	     driver.findElement(By.id("first_name")).sendKeys("Seller1");
	     Thread.sleep(1000);
	     System.out.println("First Name");
	     Thread.sleep(1000);	    
	     driver.findElement(By.id("save")).click();
	     Thread.sleep(1000);
	     System.out.println("save");
	     JavascriptExecutor jt = (JavascriptExecutor) driver;
	     jt.executeScript("window.scrollBy(0,300)", "");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[2]/div/div/div[16]/div/div/button")).click();
	     System.out.println("A/C History");
	     Thread.sleep(1000);	     
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[1]/div[2]/p")).click();
	     Thread.sleep(1000);
	     driver.findElement(By.id("phoneCode")).sendKeys("IND [+91]");
	     System.out.println("Code");
	     Thread.sleep(1000);
	     driver.findElement(By.id("mobile_no")).sendKeys("9100180088");	
	     System.out.println("Number");
	     Thread.sleep(1000);
	     driver.findElement(By.id("country")).sendKeys("United Kingdom");
	     System.out.println("Country");
	     Thread.sleep(1000);
	     driver.findElement(By.id("state")).sendKeys("Wales");
	     System.out.println("State");
	     Thread.sleep(1000);
	     driver.findElement(By.id("city")).sendKeys("Hyderabad");
	     System.out.println("City");
	     Thread.sleep(1000);
	     driver.findElement(By.id("street")).sendKeys("Punjagutta");
	     System.out.println("Street");
	     Thread.sleep(1000);
	     driver.findElement(By.id("pincode")).sendKeys("505503");
	     System.out.println("Pincode");
	     Thread.sleep(1000);
	     driver.findElement(By.id("organization")).sendKeys("DaaZ");
	     System.out.println("Organization");
	     Thread.sleep(1000);
	     driver.findElement(By.id("about")).sendKeys("Domain");
	     System.out.println("About");
	     Thread.sleep(1000);
	     driver.findElement(By.id("company_no")).clear();	    
	     driver.findElement(By.id("company_no")).sendKeys("040-9887773");
	     System.out.println("Company number");
	     Thread.sleep(1000);
	     driver.findElement(By.id("vat_no")).clear();
	     driver.findElement(By.id("vat_no")).sendKeys("9875654");
	     System.out.println("VAT");
	     Thread.sleep(1000);
	     driver.findElement(By.id("save_address")).click();
	     System.out.println("Address");
	     Thread.sleep(1000);
	     driver.navigate().refresh();
	     Thread.sleep(3000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[1]/div[2]/p")).click();
	     Thread.sleep(1000);
	     JavascriptExecutor jt1 = (JavascriptExecutor) driver;
	     jt1.executeScript("window.scrollBy(0,600)", "");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[3]/div/div/div[9]/div[1]/button")).click();
	     Thread.sleep(1000);
	     System.out.println("Building History");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[3]/div/div/div[9]/div[2]/button")).click();
	     System.out.println("Company Hostory");
	     Thread.sleep(1000);    
	     driver.navigate().refresh();
	     Thread.sleep(3000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[1]/div[3]/p")).click();
	     Thread.sleep(1000);
	     System.out.println("Payout Details");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[4]/div[2]/div[1]/label")).click();
	     Thread.sleep(1000);
	     System.out.println("Balance");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[4]/div[2]/div[2]/label")).click();
	     Thread.sleep(1000);
	     System.out.println("Bank Transfer");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[4]/div[2]/div[3]/label")).click();
	     Thread.sleep(1000);
	     System.out.println("PayPal");
	     driver.findElement(By.id("country_bank")).sendKeys("United Kingdom");
	     Thread.sleep(1000);
	     System.out.println("Country Name");
	     driver.findElement(By.id("account_type")).sendKeys("Business Account");	
	     Thread.sleep(1000);
	     System.out.println("Account Type");
	     driver.findElement(By.id("account_name")).sendKeys("Rakesh");	
	     Thread.sleep(1000);
	     System.out.println("Account Name");
	     driver.findElement(By.id("bank_name")).sendKeys("American");	
	     Thread.sleep(1000);
	     System.out.println("Bank Name");
	     driver.findElement(By.id("account_no")).sendKeys("6230577889");	
	     Thread.sleep(1000);
	     System.out.println("Account Number");
	     driver.findElement(By.id("swift_code")).sendKeys("6809656");	
	     Thread.sleep(1000);
	     System.out.println("Code");
	     driver.findElement(By.id("paypal_email")).clear();
	     System.out.println("Mail Clear");	   
	     driver.findElement(By.id("paypal_email")).sendKeys("rakeshuppula32@gmail.com");	
	     Thread.sleep(1000);	     
	     System.out.println("PayPal Mail");
	     driver.findElement(By.id("confirm_paypal_email")).clear();
	     System.out.println("Mail Clear2");
	     driver.findElement(By.id("confirm_paypal_email")).sendKeys("rakeshuppula32@gmail.com");
	     Thread.sleep(1000);	     
	     System.out.println("Paypal mail confirm");
	     driver.findElement(By.id("save_payment_details")).click();
	     Thread.sleep(1000);
	     System.out.println("Save");
	     JavascriptExecutor jt2 = (JavascriptExecutor) driver;
	     jt2.executeScript("window.scrollBy(0,1000)", "");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[4]/div[10]/div/div[1]/button")).click();
	     Thread.sleep(1000);
	     System.out.println("PayOut Method History");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[4]/div[10]/div/div[2]/button")).click();
	     Thread.sleep(1000);
	     System.out.println("Ali Pay Method History");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[4]/div[10]/div/div[3]/button")).click();
	     Thread.sleep(1000);
	     System.out.println("Bank Transfer History");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[4]/div[10]/div/div[4]/button")).click();
	     Thread.sleep(1000);
	     System.out.println("Bit Coin Wallet History");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[4]/div[10]/div/div[5]/button")).click();
	     System.out.println("PayPal Account History");
	     Thread.sleep(1000);  
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[1]/div[4]/p")).click();
	     Thread.sleep(1000);
	     System.out.println("Sale Page");
	     driver.findElement(By.id("price_option")).sendKeys("Make an offer");	
	     Thread.sleep(1000);
	     driver.findElement(By.id("start_offer")).clear();
	     Thread.sleep(1000);
	     driver.findElement(By.id("start_offer")).sendKeys("100");
	     Thread.sleep(1000);
	     driver.findElement(By.id("currency")).sendKeys("EUR");
	     Thread.sleep(1000);
	     driver.findElement(By.id("theme")).sendKeys("Simple");
	     Thread.sleep(1000);
	     driver.findElement(By.id("notes_txt")).sendKeys("vinnu");
	     Thread.sleep(1000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[5]/div[6]/label"));
	     Thread.sleep(1000);
	     driver.findElement(By.id("buying_option_details")).click();	     
	     Thread.sleep(1000);     
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[1]/div[5]/p")).click();
	     System.out.println("Store");
	     Thread.sleep(3000);
	     String parentWindowHandle=driver.getWindowHandle();
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[6]/div[1]/div[2]/div/a")).click();	    
	     Set<String>windowHandles=driver.getWindowHandles();
	     for(String windowHandle : windowHandles) {
         if(!windowHandle.equals(parentWindowHandle)) {
         driver.switchTo().window(windowHandle);
         Thread.sleep(3000);
         driver.close();
         }
	     }
	     driver.switchTo().window(parentWindowHandle);    
	     Thread.sleep(1000); 
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[6]/div[3]/div[1]/div/div[2]/label")).click();
	     Thread.sleep(1000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[6]/div[3]/div[1]/div/div[1]/label")).click();
	     Thread.sleep(1000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[6]/div[3]/div[2]/div[1]/div/div[1]/label")).click();
	     Thread.sleep(1000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[6]/div[3]/div[2]/div[1]/div/div[2]/label")).click();
	     Thread.sleep(1000);
	     driver.findElement(By.id("choose_nick_name")).click();
	     Thread.sleep(1000);
	     driver.findElement(By.id("nick_name")).sendKeys("Rakesh");
	     Thread.sleep(1000);
	     //driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[6]/div[3]/div[2]/div[2]/div/div[2]/label")).click();
	     Thread.sleep(1000);
	     driver.findElement(By.id("public_profile_notes_txt")).sendKeys("What Happen Without Testing");
	     Thread.sleep(1000);
	     driver.findElement(By.id("privacy_details")).click();
	     Thread.sleep(1000);	     
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[1]/div[6]/p")).click();
	     System.out.println("Privacy");
	     Thread.sleep(1000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[7]/div[2]/div/div[2]/div[3]/div/label")).click();
	     Thread.sleep(1000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[7]/div[2]/div/div[2]/div[4]/div/label")).click();
	     Thread.sleep(1000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[7]/div[2]/div/div[2]/div[5]/div/label[2]")).click();
	     Thread.sleep(1000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[7]/div[2]/div/div[2]/div[6]/div/label[2]")).click();
	     Thread.sleep(1000);
	     driver.findElement(By.id("save_privacy_details")).click();
	     Thread.sleep(1000);
	     driver.findElement(By.id("save_whatsapp")).click();
	     Thread.sleep(1000);	     
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[1]/div[7]/p")).click();
	     System.out.println("External");
	     Thread.sleep(1000);
	     driver.findElement(By.id("save_external_details")).click();
	     Alert rakesh=driver.switchTo().alert();
	     rakesh.dismiss();
	     
           
	     }
         }
