package Only_UI_DEV;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.util.ArrayList;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
public class D3_Auction_Bidding {
	public static void main(String[] args) throws Exception {		
		System.setProperty("webdriver.gecko.driver","./Resources/geckodriver.exe");
		WebDriver driver=new FirefoxDriver();
		driver.navigate().to("https://dev:Devserver@1956!2023@d-v.in/portfolio");
		Thread.sleep(3000);
		driver.findElement(By.id("username")).sendKeys("Rakeshuppula3+buyer@gmail.com");
		driver.findElement(By.id("password")).sendKeys("Rakesh1800##@@");
		driver.switchTo().frame("mtcaptcha-1-iframe-1");
		driver.findElement(By.id("mtcap-inputtext-1")).click();
		driver.switchTo().defaultContent();
		Thread.sleep(10000);
		driver.findElement(By.id("login_submit")).click();
		System.out.println("Seller login");
		Thread.sleep(5000);
		driver.findElement(By.xpath("/html/body/nav/div[1]/div[2]/div/div[2]/div[1]/ul/li[3]/a")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div/div[2]/div/div[5]/div[2]/div[2]/div[1]/table/tbody/tr[1]/td[6]/a")).click();
		Thread.sleep(3000);
		ArrayList<String> y1=new ArrayList<String>(driver.getWindowHandles());
		driver.switchTo().window(y1.get(1));
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[2]/div[1]/div/div[2]/div/form/input")).sendKeys("20");
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[2]/div[1]/div/div[2]/div/span/button")).click();
		Thread.sleep(2000);
		Robot r = new Robot();
	    r.keyPress(KeyEvent.VK_ENTER);
	    r.keyRelease(KeyEvent.VK_ENTER);	
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[2]/div[1]/div/div[2]/div/form/input")).clear();
		driver.findElement(By.name("the-bid")).sendKeys("30");
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[2]/div[1]/div/div[2]/div/span/button")).click();
		Thread.sleep(2000);	
		Robot r1 = new Robot();
	    r1.keyPress(KeyEvent.VK_ENTER);
	    r1.keyRelease(KeyEvent.VK_ENTER);		
		Thread.sleep(3000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[2]/div[1]/div/div[2]/div/form/input")).clear();
		driver.findElement(By.name("the-bid")).sendKeys("40");
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[2]/div[1]/div/div[2]/div/span/button")).click();
		Thread.sleep(2000);
		Robot r2 = new Robot();
	    r2.keyPress(KeyEvent.VK_ENTER);
	    r2.keyRelease(KeyEvent.VK_ENTER);		
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[2]/div[1]/div/div[2]/div/form/input")).clear();
		driver.findElement(By.name("the-bid")).sendKeys("50");
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[2]/div[1]/div/div[2]/div/span/button")).click();
		Thread.sleep(2000);
		Robot r2e = new Robot();
	    r2e.keyPress(KeyEvent.VK_ENTER);
	    r2e.keyRelease(KeyEvent.VK_ENTER);		
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[2]/div[1]/div/div[2]/div/form/input")).clear();
		driver.findElement(By.name("the-bid")).sendKeys("60");
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[2]/div[1]/div/div[2]/div/span/button")).click();
		Thread.sleep(2000);
		Robot r2r = new Robot();
	    r2r.keyPress(KeyEvent.VK_ENTER);
	    r2r.keyRelease(KeyEvent.VK_ENTER);		
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[2]/div[1]/div/div[2]/div/form/input")).clear();
		driver.findElement(By.name("the-bid")).sendKeys("70");
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[2]/div[1]/div/div[2]/div/span/button")).click();
		Thread.sleep(2000);
		Robot r28 = new Robot();
	    r28.keyPress(KeyEvent.VK_ENTER);
	    r28.keyRelease(KeyEvent.VK_ENTER);		
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[2]/div[1]/div/div[2]/div/form/input")).clear();
		driver.findElement(By.name("the-bid")).sendKeys("80");
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[2]/div[1]/div/div[2]/div/span/button")).click();
		Thread.sleep(2000);
		Robot r2r1 = new Robot();
	    r2r1.keyPress(KeyEvent.VK_ENTER);
	    r2r1.keyRelease(KeyEvent.VK_ENTER);		
		Thread.sleep(2000);
//Admin
		System.out.println("***** ADMIN SIDE *****");// Admin side	********************************************************8	
		 driver.navigate().to("http://dev:Devserver@1956!2023@admin.d-v.in/admin/dashboard");
	     Thread.sleep(1000);	    
	     driver.findElement(By.xpath("//input[@id='username']")).sendKeys("Dev_DaaZ_Admin");
	     Thread.sleep(2000);
	     System.out.println("Enter Mail");	     
	     driver.findElement(By.xpath("//input[@id='password']")).sendKeys("Pesu@1956!2021"); 
	     Thread.sleep(2000);
	     System.out.println("Enter Password");	   
	     driver.findElement(By.xpath("//button[@id='signInBtn']")).click();	     
	     Thread.sleep(1000);
	     driver.navigate().refresh();
	     System.out.println("Enter Submit");	     
	     Thread.sleep(2000);
		 driver.findElement(By.xpath("//span[normalize-space()='Manage Sales Activities']")).click();
		 Thread.sleep(2000);
		 System.out.println("Clicked on Manage Sales");
		 driver.findElement(By.xpath("//li[contains(@class,'open')]//ul[contains(@class,'sub-menu')]//a[contains(@class,'nav-link nav-toggle')]")).click();
		 Thread.sleep(2000);
		 System.out.println("Clicked on Auction");
		 driver.findElement(By.xpath("//a[contains(@href,'/admin/auction-details')]")).click();
		 Thread.sleep(2000);
		 System.out.println("Clicked on All Auction ");
		 driver.findElement(By.xpath("/html/body/div[1]/div[4]/div[1]/div/ul/li[6]/ul/li[5]/ul/li[1]/a")).click();
		 Thread.sleep(2000);
		 driver.findElement(By.xpath("/html/body/div[1]/div[4]/div[2]/div/div[2]/div/div/div/div/div/div[2]/table/tbody/tr[1]/td[14]/a")).click();
		 Thread.sleep(2000);
		 ArrayList<String> RT2=new ArrayList<String>(driver.getWindowHandles());
		 driver.switchTo().window(RT2.get(2));
		 Thread.sleep(2000);		
		 driver.findElement(By.xpath("/html/body/div[1]/div[4]/div[2]/div/div[2]/div/div/div/div[3]/button")).click();
		 Thread.sleep(2000);
		 driver.findElement(By.id("message-text")).sendKeys("test");
		 Thread.sleep(2000);
		 driver.findElement(By.xpath("/html/body/div[1]/div[4]/div[2]/div/div[3]/div/div/div[3]/button[1]")).click();
		 Thread.sleep(2000);
		 Alert at2=driver.switchTo().alert();
		 at2.accept();
		 Thread.sleep(2000);
		 ArrayList<String> y5=new ArrayList<String>(driver.getWindowHandles());
		 driver.switchTo().window(y5.get(0));
		 Thread.sleep(2000);
		 driver.findElement(By.xpath("/html/body/nav/div[1]/div[2]/div/div[2]/div[1]/ul/li[1]/a")).click();
		 Thread.sleep(2000);
		 driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[1]/ul/li[3]/a")).click();
		 Thread.sleep(2000);
		 driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[1]/div[2]/p")).click();
		 Thread.sleep(2000);
		 driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div/div[2]/div[3]/div[3]/div[3]/div/div[2]/div/div[1]/table/tbody/tr[1]/td[8]/a[3]")).click();
		 Thread.sleep(2000);
		 ArrayList<String> y6=new ArrayList<String>(driver.getWindowHandles());
		 driver.switchTo().window(y6.get(1));
		 Thread.sleep(2000);
//Buy now Page***************		 
		 JavascriptExecutor j1tw = (JavascriptExecutor) driver;
	 	 j1tw.executeScript("window.scrollBy(0,300)", "");
	 	 Thread.sleep(1000);
		 driver.findElement(By.xpath("/html/body/div[1]/div/div/div[1]/div[2]/div[3]/div/div[1]/div[2]/div[3]/div[2]/div/ul/li[2]/div/label/span")).click();
		 Thread.sleep(3000);
		    
		 try {
		 driver.findElement(By.xpath("/html/body/div[1]/div/div/div[1]/div[2]/div[3]/div/div[1]/div[2]/div[3]/div[2]/div/ul/li[2]/div/label/span/b")).click();
		 Thread.sleep(3000);
		 }catch(Exception e) {
		 JavascriptExecutor jtw = (JavascriptExecutor) driver;
		 jtw.executeScript("window.scrollBy(0,100)", "");
		 Thread.sleep(1000);
		 }
		 try {
		 driver.findElement(By.xpath("/html/body/div[1]/div/div/div[1]/div[2]/div[3]/div/div[1]/div[2]/div[3]/div[2]/div/ul/li[2]/div/label/span/b")).click();
	     Thread.sleep(3000);
		 }catch(Exception e) {		    	
		 }
		 Thread.sleep(3000);
	     System.out.println("Selected stripe");
	     driver.findElement(By.xpath("/html/body/div[1]/div/div/div[1]/div[2]/div[3]/div/div[1]/div[2]/div[3]/div[2]/div/ul/li[2]/button")).click();
	     Thread.sleep(2000);	       
	     Thread.sleep(2000);
		 driver.findElement(By.name("cardNumber")).sendKeys("4242424242424242");
		 System.out.println("Payment Done");
		 Thread.sleep(3000);
		 driver.findElement(By.name("cardExpiry")).sendKeys("333");
		 Thread.sleep(1000);
		 driver.findElement(By.name("cardCvc")).sendKeys("029");
		 Thread.sleep(1000);     
		 driver.findElement(By.name("billingName")).sendKeys("Rakesh");
		 Thread.sleep(1000);
		 JavascriptExecutor jt8 = (JavascriptExecutor) driver;
	     jt8.executeScript("window.scrollBy(0,100)", "");
		 Thread.sleep(1000);
		 driver.findElement(By.xpath("/html/body/div[1]/div/div/div[2]/main/div/form/div[1]/div/div/div[3]/div/div[2]/button/div[3]")).click();
		 Thread.sleep(6000);
		 
		 driver.quit();
	}
}
