package Only_UI_DEV;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

public class K_Traffic_Reports {

	public static void main(String[] args) throws Exception {
		System.setProperty("webdriver.gecko.driver","./Resources/geckodriver.exe");
		WebDriver driver=new FirefoxDriver();
		driver.manage().window().maximize();
		driver.navigate().to("https://dev:Devserver@1956!2023@d-v.in/traffic/report");
	    Thread.sleep(1000);	    
	     //driver.findElement(By.xpath("/html/body/nav/div[1]/div[2]/div/div[2]/div[2]/ul/li[1]/a")).click();
	     System.out.println("Click on Login Button");
	     driver.findElement(By.id("username")).sendKeys("rakeshuppula3@gmail.com");
	     Thread.sleep(1000);
	     driver.findElement(By.id("password")).sendKeys("Rakesh1800##@@");
	     driver.switchTo().frame("mtcaptcha-1-iframe-1");
		 driver.findElement(By.id("mtcap-inputtext-1")).click();
		 driver.switchTo().defaultContent();
	     Thread.sleep(10000);
	     driver.findElement(By.id("login_submit")).click();
	     System.out.println("LOGIN successfully");
	     Thread.sleep(3000);
	     driver.findElement(By.id("page_length")).sendKeys("500");
	     System.out.println("choose 500");
	     Thread.sleep(3000);
	     WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/b"));
	     System.out.println("1 ="+e.getText());
	    // Thread.sleep(1000);
	     driver.findElement(By.id("page_length")).sendKeys("All");
	     System.out.println("Choose All");
	     Thread.sleep(3000);
	     WebElement e1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/b"));
	     System.out.println("2 ="+e1.getText());
	    // Thread.sleep(1000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[1]/div[2]/div[2]/button")).click();
	     System.out.println("Clcked on Export Button");
	     
	     Thread.sleep(7000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/a")).click();
	     System.out.println("Click on Calender");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/div/div/div/ul/li[1]/a")).click();
	     System.out.println("Choosed Today");
	     Thread.sleep(5000);
	     WebElement e2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/b"));
	     System.out.println("3 ="+e2.getText());
	     
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/a")).click();
	     System.out.println("Click on Calender");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/div/div/div/ul/li[2]/a")).click();
	     System.out.println("Choosed Yesterday");
	     Thread.sleep(5000);
	     WebElement e3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/b"));
	     System.out.println("4 ="+e3.getText());
	    // Thread.sleep(3000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/a")).click();
	     System.out.println("Click on Calender");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/div/div/div/ul/li[3]/a")).click();
	     System.out.println("Choosed 7 Days");
	     Thread.sleep(5000);
	     WebElement e4=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/b"));
	     System.out.println("5 ="+e4.getText());
	    // Thread.sleep(3000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/a")).click();
	     System.out.println("Click on Calender");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/div/div/div/ul/li[4]/a")).click();
	     System.out.println("Choosed 30 Days");
	     Thread.sleep(5000);
	     WebElement e5=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/b"));
	     System.out.println("6 ="+e5.getText());
	   //  Thread.sleep(3000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/a")).click();
	     System.out.println("Click on Calender");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/div/div/div/ul/li[5]/a")).click();
	     System.out.println("Choosed 90 Days");
	     Thread.sleep(5000);
	     WebElement e6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/b"));
	     System.out.println("7 ="+e6.getText());
	    // Thread.sleep(3000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/a")).click();
	     System.out.println("Click on Calender");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/div/div/div/ul/li[6]/a")).click(); 
	     System.out.println("Choosed All");
	     Thread.sleep(5000);
	     WebElement e7=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/b"));
	     System.out.println("8 ="+e7.getText());
	   //  Thread.sleep(3000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/a")).click();
	     System.out.println("Click on Calender");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[1]/div[2]/p")).click();
	     System.out.println("Clicked on Time Period");
	     Thread.sleep(5000);
	     WebElement e8=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/b"));
	     System.out.println("9="+e8.getText());
	    // Thread.sleep(3000);
	     driver.findElement(By.id("page_length1")).sendKeys("500");
	     System.out.println("choose 500");
	     Thread.sleep(5000);
	     WebElement e9=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/b"));
	     System.out.println("10 ="+e9.getText());
	    // Thread.sleep(1000);
	     driver.findElement(By.id("page_length1")).sendKeys("All");
	     System.out.println("Choose All");
	     Thread.sleep(5000);
	     WebElement e10=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/b"));
	     System.out.println("11 ="+e10.getText());
	    // Thread.sleep(3000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[3]/div[1]/div/button")).click();
	     Thread.sleep(5000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[3]/div[2]/div/div/a")).click();
	     System.out.println("Click on Calender");
	     Thread.sleep(3000);
	     
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div/div/ul/li[1]/a")).click();
	     System.out.println("Choosed Today");
	     Thread.sleep(5000);
	     WebElement e11=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/b"));
	     System.out.println("12="+e11.getText());
	     //Thread.sleep(3000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[3]/div[2]/div/div/a")).click();
	     System.out.println("Click on Calender");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div/div/ul/li[2]/a")).click();
	     System.out.println("Choosed Yesterday");
	     Thread.sleep(5000);
	     WebElement e12=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/b"));
	     System.out.println("13 ="+e12.getText());
	    // Thread.sleep(3000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[3]/div[2]/div/div/a")).click();
	     System.out.println("Click on Calender");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div/div/ul/li[3]/a")).click();
	     System.out.println("Choosed 7 Days");
	     Thread.sleep(5000);
	     WebElement e13=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/b"));
	     System.out.println("14 ="+e13.getText());
	     //Thread.sleep(3000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[3]/div[2]/div/div/a")).click();
	     System.out.println("Click on Calender");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div/div/ul/li[4]/a")).click();
	     System.out.println("Choosed 30 Days");
	     Thread.sleep(5000);
	     WebElement e14=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/b"));
	     System.out.println("15 ="+e14.getText());
	    // Thread.sleep(3000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[3]/div[2]/div/div/a")).click();
	     System.out.println("Click on Calender");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div/div/ul/li[5]/a")).click();
	     System.out.println("Choosed 90 Days");
	     Thread.sleep(5000);
	     WebElement e15=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/b"));
	     System.out.println("16 ="+e15.getText());
	    // Thread.sleep(3000);
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[3]/div[2]/div/div/a")).click();
	     System.out.println("Click on Calender");
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div/div/ul/li[6]/a")).click(); 
	     System.out.println("Choosed All");
	     Thread.sleep(5000);
	     WebElement e16=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/b"));
	     System.out.println("18 ="+e16.getText());
	     //Thread.sleep(3000); 
	     driver.findElement(By.xpath("/html/body/div[1]/div[1]/div/div/div[2]/div[2]/div[1]/div[3]/p")).click();
	     Thread.sleep(3000);
	     driver.quit();
	     
	     
	     
	     
	     
	}

}
